import re
from typing import Any


def normalize_document_faq_text(text: str) -> str:
    text = text.replace("“", "\"").replace("”", "\"").replace("’", "\'").replace("–", "-").replace("—", "-")
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"^[\"\']+", "", text)
    text = re.sub(r"[?!.]+$", "", text).strip()
    text = re.sub(r"^[\"\']+", "", text)
    text = re.sub(r"[\"\']+$", "", text)
    return text.lower().strip()


PBSG_DOCUMENT_FAQS: dict[str, dict[str, Any]] = {
    'faq_005': {
        'number': '005',
        'question': 'What is Pro Bono SG?',
        'match_texts': ['tell me more about pro bono sg', 'what is pbsg', 'what is pro bono sg', 'who is pro bono sg'],
        'answer': 'Pro Bono SG is a charity that helps people who cannot afford legal assistance with their personal legal issues. We provide legal guidance, connect individuals to volunteer lawyers, and may offer legal representation through specific schemes.',
        'source_ids': [],
    },
    'faq_007': {
        'number': '007',
        'question': 'What are your operating hours?',
        'match_texts': ['what are your opening hours', 'what are your operating hours'],
        'answer': 'Hotline operating hours:\\nMonday to Friday\\n10:00am – 1:00pm\\n2:00pm – 4:00pm\\nClosed on public holidays\\nHelp Centre (Headquarters) and Community Law Centres opening hours:\\nMonday to Friday\\n9:00am – 12:00pm\\n2:00pm – 5:00pm\\nClosed on public holidays\\nMigrant Workers’ Law Centre @ MWC opening hours:\\nMonday (virtual only – please call 8764 8298)\\n9:00am – 5:45pm\\nTuesday to Friday\\n9:00am – 5:45pm\\nSaturday (virtual only – please call 8764 8298)\\n11:00am – 3:00pm\\nClosed on public holidays\\nMigrant Workers’ Legal Clinic @ Angullia Mosque opening hours:\\n2nd Sundays of the month\\n10:00am – 12:30pm',
        'source_ids': [],
    },
    'faq_029': {
        'number': '029',
        'question': 'What is your address? Can I walk in?',
        'match_texts': ['can i walk in', 'what is your address', 'what is your address? can i walk in', 'where is the pbsg counter'],
        'answer': 'Help Centre (Headquarters):\\n1 Havelock Square\\n#B1-18, State Courts\\nSingapore 059724\\nCommunity Law Centre @ Tian De Temple (Hougang):\\n109 Hougang Avenue 5\\nSingapore 538817\\nCommunity Law Centre @ Realm of Tranquility (Woodlands):\\nBlk 547 Woodlands Drive 16\\n#01-177\\nSingapore 730547\\nMigrant Workers’ Law Centre @ MWC:\\n579 Serangoon Road\\nSingapore 218193\\nPBSG generally operates by appointment only. The enquirer may still choose to walk-in, but may not be able to meet with a lawyer on the same day. Consider letting the enquirer know: “Since we are already on the line, perhaps I can better understand your situation first before letting you know how best we may be able to help?”',
        'source_ids': [],
    },
    'faq_045': {
        'number': '045',
        'question': 'How long is the waiting time for my appointment?',
        'match_texts': ['how long is the waiting time for my appointment'],
        'answer': 'It depends on the enquirer’s case and the availability of our services. If the enquirer is able to answer a few questions to help us determine the type of service needed, we can provide an estimated timeline.\\nB. Services and Scope',
        'source_ids': [],
    },
    'faq_048': {
        'number': '048',
        'question': 'What is the difference between legal guidance and legal representation?',
        'match_texts': ['what is the difference between legal guidance and legal representation'],
        'answer': 'Legal guidance usually refers to a one-off consultation, often about 20 minutes, where a lawyer provides general legal guidance on the enquirer’s issue.\\nAt these sessions:\\nThe lawyer does not act for the enquirer.\\nThe lawyer will not comprehensively review all documents.\\nThe lawyer will not draft documents during the session.\\nThe session is generally one-off.\\nLegal representation means a lawyer may act for the enquirer over a period of time, including in court, if the enquirer qualifies for a representation scheme.',
        'source_ids': [],
    },
    'faq_056': {
        'number': '056',
        'question': 'Can you give legal guidance over the phone or by email?',
        'match_texts': ['can you give legal guidance over the phone or by email'],
        'answer': 'PBSG can provide general information about legal help services and guide the enquirer to a suitable avenue of help. For legal guidance by a lawyer, the enquirer will first need to register and provide basic information about the case and circumstances so PBSG can assess eligibility. If the enquirer qualifies, PBSG may then arrange a consultation with a lawyer who can provide general legal guidance either in-person or over a virtual call.',
        'source_ids': [],
    },
    'faq_058': {
        'number': '058',
        'question': 'Can you represent me in court?',
        'match_texts': ['can you represent me in court'],
        'answer': 'PBSG may be able to provide legal representation depending on the enquirer’s eligibility and the type of case. If the enquirer is able to answer a few questions, we can provide more information on the avenues of help which may be available.',
        'source_ids': [],
    },
    'faq_060': {
        'number': '060',
        'question': 'Can you help with business matters?',
        'match_texts': ['can you help with business matters'],
        'answer': 'PBSG’s services are generally for personal legal issues. PBSG generally does not assist with business or corporate matters unless one of the following applies:\\nThe matter concerns a non-profit, charity, social enterprise, or ground-up initiative.\\nThe enquirer is personally liable in relation to the issue, for example as a sole proprietor, a personal guarantor for a business loan, a person facing bankruptcy, or a person charged in a personal capacity for a criminal offence.\\nFor non-profit or similar matters, the enquirer may email nls@probono.sg. The frontliner may also take down the entity name, contact details, and legal issue for follow-up. Eligibility criteria link: https://www.probono.sg/wp-content/uploads/2025/07/3.7.25.pdf\\nC. Means Testing and Common Financial Terms',
        'source_ids': [],
    },
    'faq_066': {
        'number': '066',
        'question': 'How do you decide if I qualify?',
        'match_texts': ['how do you decide if i qualify'],
        'answer': 'Eligibility depends on the service or scheme. PBSG may consider:\\nThe nature of the legal issue.\\nWhether the enquirer is seeking personal legal help or something outside PBSG’s scope.\\nWhether the enquirer is eligible for a Government legal aid scheme such as LAB or PDO.\\nWhether the enquirer is currently legally represented or has sought legal help on the same issue before.\\nThe enquirer’s financial circumstances.\\nFor legal representation, whether the case has legal merits.\\nIf the enquirer is able to answer a few questions, we can provide more information on a suitable avenue of help and its eligibility criteria.',
        'source_ids': [],
    },
    'faq_075': {
        'number': '075',
        'question': 'Can I still get help if I am not a Singapore Citizen or PR?',
        'match_texts': ['can i still get help if i am not a singapore citizen or pr'],
        'answer': 'Generally, PBSG assists individuals of all nationalities. Specific eligibility differs from scheme to scheme. If the enquirer is able to answer a few questions, we can provide more information on a suitable avenue of help and its eligibility criteria.',
        'source_ids': [],
    },
    'faq_077': {
        'number': '077',
        'question': 'Can I still get help if I am overseas?',
        'match_texts': ['can i still get help if i am overseas'],
        'answer': 'PBSG may still be able to assist, but more details will be needed.\\nFor legal guidance, if the enquirer meets the relevant criteria, a virtual consultation may sometimes be arranged.\\nFor legal representation, the enquirer may still submit the relevant registration form, but should explain why the enquirer is overseas, whether the enquirer can return to Singapore for court proceedings if necessary, and if not, why not.',
        'source_ids': [],
    },
    'faq_081': {
        'number': '081',
        'question': 'What is PCHI?',
        'match_texts': ['what is pchi'],
        'answer': 'PCHI means average Per Capita Gross Monthly Household Income. It is the average gross household income for the last 12 months divided by the total number of household members, including the enquirer.\\n“Gross income” generally refers to gross wages or salary before deduction of CPF contributions and income tax. It may include basic wages, overtime pay, commissions, tips, allowances, and bonuses. For self-employed persons, it generally refers to profits from the business, trade, or profession, that is, total receipts less business expenses, before tax.\\n“Household members” generally refers to persons related by blood, marriage, and/or legal adoption who share the same residential address on the relevant records.\\nExample: If one spouse earns $2,000 a month and the other spouse also earns $2,000 a month, and both live with 2 children who are not working, the PCHI is $(2,000 + 2,000) ÷ 4 = $1,000.\\nReference: https://lab.mlaw.gov.sg/legal-services/taking-the-means-test/ (PBSG calculates PCHI the same way as LAB and PDO)',
        'source_ids': [],
    },
    'faq_087': {
        'number': '087',
        'question': 'What is Annual Value?',
        'match_texts': ['what is annual value'],
        'answer': 'Annual Value refers to the Annual Value of the enquirer’s place of residence if it is owned by the enquirer.\\nThe Annual Value is the estimated gross annual rent of the property if it were rented out, excluding furniture, furnishings, and maintenance fees. It is based on estimated market rentals of similar properties, not actual rental collected.\\nThe current and past Annual Values can usually be checked by logging into IRAS and selecting “View Property Summary”.\\nMore information: https://www.iras.gov.sg/taxes/property-tax/property-owners/annual-value\\nReference point mentioned in the supplied materials: most HDB flats have an Annual Value under $21,000. See also: https://ask.gov.sg/moh/questions/cm2vqalb6002b66lwndim04n6',
        'source_ids': [],
    },
    'faq_093': {
        'number': '093',
        'question': 'How are savings and non-CPF investments calculated?',
        'match_texts': ['how are savings and non-cpf investments calculated'],
        'answer': 'This is generally done by adding the value of assets that the enquirer owns in the enquirer’s name, including:\\nSavings in bank accounts, whether personal or joint.\\nThe value of shares in the enquirer’s Central Depository (CDP) account.\\nOther financial or investment products with a cash value, such as fixed deposits, shares, bonds, or exchange traded funds.\\nReference: https://lab.mlaw.gov.sg/legal-services/taking-the-means-test/',
        'source_ids': [],
    },
    'faq_099': {
        'number': '099',
        'question': 'I have been rejected by PBSG. Is there any way to appeal for legal help, or can you help if I just miss the means test by a bit?',
        'match_texts': ['i have been rejected by pbsg. is there any way to appeal for legal help, or can you help if i just miss the means test by a bit'],
        'answer': 'Please write in with the information you would like us to further consider.\\nlegalclinics@probono.sg for clinic-related matters\\nclas@probono.sg for CLAS matters\\nfjss@probono.sg for FJSS matters\\nhelp@probono.sg if the enquirer is unsure which PBSG scheme is relevant\\nD. Legal Aid Bureau (LAB)',
        'source_ids': [],
    },
    'faq_106': {
        'number': '106',
        'question': 'What is LAB?',
        'match_texts': ['what is lab'],
        'answer': 'The Legal Aid Bureau is the Government’s legal aid agency under the Ministry of Law. It provides legal help to low-income Singaporeans and Permanent Residents for family and civil legal matters.\\nPro Bono SG is a charity. It is not the Government and it is not LAB.\\nFor questions about LAB’s own policies or decisions, the enquirer should check directly with LAB.\\nLAB website: https://lab.mlaw.gov.sg/',
        'source_ids': [],
    },
    'faq_111': {
        'number': '111',
        'question': 'What is the difference between LAB and PBSG?',
        'match_texts': ['what is the difference between lab and pbsg'],
        'answer': 'LAB is a Government legal aid agency under the Ministry of Law. PBSG is a charity.\\nFor low-income Singaporeans and Permanent Residents who need civil or family legal representation, LAB should generally be the first port of call.\\nPBSG is a charity with limited resources and needs to prioritise those who are unable to receive help elsewhere.',
        'source_ids': [],
    },
    'faq_115': {
        'number': '115',
        'question': 'Who can apply for LAB?',
        'match_texts': ['who can apply for lab'],
        'answer': 'Legal aid is available to:\\nSingapore citizens and Permanent Residents residing in Singapore.\\nCitizens or residents of contracting states who are involved in applications under the Hague Convention on the Civil Aspects of International Child Abduction.\\nFor legal advice under LAB, the enquirer must pass the means test. For legal aid or representation, the enquirer must pass both the means and merits tests. More information: https://lab.mlaw.gov.sg/legal-services/do-i-qualify/',
        'source_ids': [],
    },
    'faq_120': {
        'number': '120',
        'question': 'What is LAB’s means test?',
        'match_texts': ["what is lab's means test"],
        'answer': 'LAB’s means test assesses the enquirer’s financial circumstances to determine whether the enquirer has limited means.\\nThe thresholds reflected in the FAQ source materials for this document are:\\nAverage PCHI of $1,050 or lower for the last 12 months before the application.\\nAnnual Value of the enquirer’s place of residence owned by the enquirer of $21,000 or lower.\\nSavings and non-CPF investments of $10,000 or lower if below 60 years old, or $40,000 or lower if aged 60 and above.\\nThe enquirer must not own any other property besides the place of residence.\\nMore information: https://lab.mlaw.gov.sg/legal-services/taking-the-means-test/',
        'source_ids': [],
    },
    'faq_128': {
        'number': '128',
        'question': 'What is LAB’s merits test?',
        'match_texts': ["what is lab's merits test"],
        'answer': 'The merits test generally looks at whether the enquirer has reasonable grounds for bringing or defending the case in court.\\nMore information: https://lab.mlaw.gov.sg/legal-services/taking-the-merits-test/',
        'source_ids': [],
    },
    'faq_131': {
        'number': '131',
        'question': 'What types of cases can LAB help with?',
        'match_texts': ['what types of cases can lab help with'],
        'answer': 'Common examples include:\\nDivorce, including divorces under the Administration of Muslim Law Act.\\nVariation or enforcement of court orders on ancillary matters in a divorce, such as maintenance, division of assets, custody, care and control, and access issues.\\nAdoption.\\nCustody of children.\\nMonetary claims.\\nAppointment of a Deputy under the Mental Capacity Act.\\nClaims in tort, such as compensation for injuries from accidents or medical negligence.\\nEstate matters, including Grant of Probate and Letters of Administration.\\nProceedings before the Commissioner for Labour under the Work Injury Compensation Act.',
        'source_ids': [],
    },
    'faq_142': {
        'number': '142',
        'question': 'What types of cases does LAB not handle?',
        'match_texts': ['what types of cases does lab not handle'],
        'answer': 'LAB generally does not handle the following, among others:\\nCriminal law matters.\\nDefamation, breach of promise of marriage, or inducement of a spouse to leave another.\\nProceedings before the Small Claims Tribunal, Employment Claims Tribunal, and Tribunal for the Maintenance of Parents, where lawyers are generally not allowed.\\nMagistrate’s Complaints.\\nMost maintenance enforcement or defending against enforcement matters unless the enquirer is exceptionally vulnerable.\\nConveyancing.\\nProceedings before an arbitral tribunal.\\nApplications where the enquirer is trying to make the enquirer bankrupt.\\nSome very small civil claims.\\nSome family proceedings where the opposing party is not legally represented, unless there are exceptional circumstances.',
        'source_ids': [],
    },
    'faq_154': {
        'number': '154',
        'question': 'Can LAB help with business-related cases?',
        'match_texts': ['can lab help with business-related cases'],
        'answer': 'LAB may sometimes consider business-related cases where one or more of the following apply:\\nThe enquirer is vulnerable, for example elderly, disabled, seriously ill, poorly educated, or has limited English proficiency.\\nThe dispute concerns the enquirer’s main source of livelihood.\\nThe sum in dispute is sizeable, or the outcome would significantly affect the enquirer’s livelihood.\\nThere appears to have been unconscionable behaviour, such as fraud, undue influence, coercion, or misrepresentation.\\nThe enquirer did not voluntarily assume excessive business risk.\\nThe enquirer does not have a pattern of repeated business failures and litigation.\\nThe enquirer appears to have been wrongly included as a defendant or third party.\\nThe enquirer has not acted unconscionably.\\nA business registered sole proprietor may also be considered.',
        'source_ids': [],
    },
    'faq_165': {
        'number': '165',
        'question': 'Can LAB help if the case is urgent or there is a deadline very soon?',
        'match_texts': ['can lab help if the case is urgent or there is a deadline very soon'],
        'answer': 'In some urgent situations, the enquirer may need to take certain steps personally before LAB can open a file. Common examples reflected in the FAQ source materials include:\\nIf there are less than 5 working days to file a Notice of Appeal, the enquirer may need to file the Notice of Appeal personally first.\\nIf already out of time to appeal, the enquirer may need to obtain leave to appeal first.\\nIn civil cases where there are less than 3 working days to file a Defence, the enquirer may need to file the Defence personally first.\\nIf the enquirer has a deadline very soon, the frontliner should not try to apply LAB’s detailed internal urgency rules. The safer approach is to note the urgency and direct the enquirer promptly to LAB or urgent legal help.',
        'source_ids': [],
    },
    'faq_171': {
        'number': '171',
        'question': 'How do I apply for LAB?',
        'match_texts': ['how do i apply for lab'],
        'answer': 'The enquirer may either:\\nRegister the case online, then make an appointment within 3 working days via the OneMinLaw Portal at go.gov.sg/omp.\\nOr make an appointment directly to speak with a MinLaw or LAB officer before visiting the Ministry of Law Services Centre.\\nIf the enquirer registers online first, this may save time because details about the case and financial situation can be provided in advance. If the enquirer is a minor, a parent or guardian must generally apply on the enquirer’s behalf. Further information: https://lab.mlaw.gov.sg/legal-services/how-do-i-apply-for-legal-aid/',
        'source_ids': [],
    },
    'faq_176': {
        'number': '176',
        'question': 'What happens at the LAB appointment and what documents should the enquirer bring?',
        'match_texts': ['what happens at the lab appointment and what documents should the enquirer bring'],
        'answer': 'The enquirer should refer to LAB’s webpage for the latest appointment process and document list: https://lab.mlaw.gov.sg/legal-services/how-do-i-apply-for-legal-aid/\\nAs a general guide, LAB will usually need documents relating to the legal issue, as well as supporting documents for means testing.',
        'source_ids': [],
    },
    'faq_179': {
        'number': '179',
        'question': 'How long does LAB take to process an application?',
        'match_texts': ['how long does lab take to process an application'],
        'answer': 'It usually takes about 3 to 4 months from file opening to the decision on whether aid will be granted, but the enquirer should check with LAB to be sure.',
        'source_ids': [],
    },
    'faq_181': {
        'number': '181',
        'question': 'Does the enquirer have to pay for LAB?',
        'match_texts': ['does the enquirer have to pay for lab'],
        'answer': 'Possibly. The contribution payable usually ranges from $0 to $1,650, depending on the enquirer’s means and the complexity of the case.\\nThe enquirer may also need to pay certain other charges, such as service fees or the cost of important documents or reports.\\nReduction or waiver of contribution may sometimes be possible, subject to supporting documents.',
        'source_ids': [],
    },
    'faq_185': {
        'number': '185',
        'question': 'Can the enquirer still apply for LAB if the enquirer already has a lawyer?',
        'match_texts': ['can the enquirer still apply for lab if the enquirer already has a lawyer'],
        'answer': 'In non-urgent cases, the enquirer usually does not need to discharge the private lawyer until aid is granted. In urgent cases, discharge may happen earlier.\\nFrontliners should not advise enquirers to discharge their lawyers. That is a personal decision for the enquirer.',
        'source_ids': [],
    },
    'faq_188': {
        'number': '188',
        'question': 'What are LAB’s contact details?',
        'match_texts': ["what are lab's contact details"],
        'answer': 'LAB website: https://lab.mlaw.gov.sg/\\nHotline: 1800 2255 529\\nMinistry of Law Services Centre:\\n45 Maxwell Road\\n#07-11 The URA Centre (East Wing)\\nSingapore 069118\\nAppointments: go.gov.sg/omp\\nOperating hours:\\nMonday to Friday, 8:30am – 5:00pm\\nClosed on weekends and public holidays\\nGeneral MinLaw contact page: https://www.mlaw.gov.sg/about-us/contact-us/\\nE. Public Defender’s Office (PDO)',
        'source_ids': [],
    },
    'faq_201': {
        'number': '201',
        'question': 'What is PDO?',
        'match_texts': ['what is pdo'],
        'answer': 'PDO is the Government’s legal aid agency under the Ministry of Law for criminal matters. It provides legal help to low-income Singaporeans and Permanent Residents who have been charged in court with criminal offences.\\nPro Bono SG is a charity. It is not the Government and it is not PDO, although PBSG works closely with PDO.\\nPDO website: https://pdo.mlaw.gov.sg/',
        'source_ids': [],
    },
    'faq_205': {
        'number': '205',
        'question': 'What is the difference between PDO and PBSG?',
        'match_texts': ['what is the difference between pdo and pbsg'],
        'answer': 'PDO is a Government agency under the Ministry of Law. PBSG is a charity.\\nFor low-income Singaporeans and Permanent Residents who have been charged in court with non-capital criminal offences, PDO should generally be the first port of call.\\nPBSG, as a charity with limited resources, needs to prioritise those who cannot receive help elsewhere.',
        'source_ids': [],
    },
    'faq_209': {
        'number': '209',
        'question': 'Who qualifies for PDO?',
        'match_texts': ['who qualifies for pdo'],
        'answer': 'PDO is for enquirers who meet all of the following:\\nSingapore citizens or Permanent Residents.\\nAlready charged in court for an offence that is not excluded by PDO.\\nPass the means test.\\nPass the merits test.\\nMore information: https://pdo.mlaw.gov.sg/criminal-defence-aid/qualifying-for-help/',
        'source_ids': [],
    },
    'faq_216': {
        'number': '216',
        'question': 'What offences does PDO not handle?',
        'match_texts': ['what offences does pdo not handle'],
        'answer': 'PDO does not handle:\\nOffences punishable by death.\\nOffences that are regulatory in nature, for example traffic summonses, and departmental charges.\\nOffences under certain Acts relating to gambling, organised or syndicate crime, and terrorism.\\nOffences prosecuted by a private person.\\nReference: Public Defenders Act 2022 https://pdo.mlaw.gov.sg/files/Public_Defenders_Act_2022.pdf',
        'source_ids': [],
    },
    'faq_223': {
        'number': '223',
        'question': 'Which Acts are excluded under PDO for gambling, organised crime, and terrorism?',
        'match_texts': ['which acts are excluded under pdo for gambling, organised crime, and terrorism'],
        'answer': 'Betting Act 1960\\nCasino Control Act 2006\\nCommon Gaming Houses Act 1961\\nGambling Control Act 2022\\nMassage Establishments Act 2017\\nOrganised Crime Act 2015\\nRemote Gambling Act 2014\\nTerrorism (Suppression of Bombings) Act 2007\\nTerrorism (Suppression of Financing) Act 2002\\nTerrorism (Suppression of Misuse of Radioactive Material) Act 2017',
        'source_ids': [],
    },
    'faq_234': {
        'number': '234',
        'question': 'Which regulatory Acts are excluded under PDO?',
        'match_texts': ['which regulatory acts are excluded under pdo'],
        'answer': 'Advance Medical Directive Act 1996\\nChild Development Co-Savings Act 2001\\nCustoms Act 1960\\nEmployment Act 1968\\nEmployment Agencies Act 1958\\nEmployment Claims Act 2016\\nEmployment of Foreign Manpower Act 1990\\nEnlistment Act 1970\\nFire Safety Act 1993\\nForeign Employee Dormitories Act 2015\\nGoods and Services Tax Act 1993\\nHealth Products Act 2007\\nHealth Promotion Board Act 2001\\nHealth Sciences Authority Act 2001\\nImmigration Act 1959\\nInfectious Diseases Act 1976\\nInsolvency, Restructuring and Dissolution Act 2018\\nMedical and Elderly Care Endowment Schemes Act 2000\\nMedicines (Advertisement and Sale) Act 1955\\nMedicines Act 1975\\nMoneylenders Act 2008\\nNational Registration Act 1965\\nPassports Act 2007\\nPersonal Data Protection Act 2012\\nPoisons Act 1938\\nRegistration of Births and Deaths Act 2021\\nRegulation of Imports and Exports Act 1995\\nRetirement and Re-employment Act 1993\\nRoad Traffic Act 1961\\nSale of Drugs Act 1914\\nSingapore Armed Forces Act 1972\\nTermination of Pregnancy Act 1974\\nTobacco (Control of Advertisements and Sale) Act 1993\\nTraditional Chinese Medicine Practitioners Act 2000\\nWork Injury Compensation Act 2019\\nWorkplace Safety and Health Act 2006\\nTown Councils Act 1988\\nBankruptcy Act (Cap 20, 2009 Rev Ed)\\nPawnbrokers Act 2015',
        'source_ids': [],
    },
    'faq_274': {
        'number': '274',
        'question': 'What is PDO’s means test?',
        'match_texts': ["what is pdo's means test"],
        'answer': 'Average PCHI of $1,650 or lower for the last 12 months before the application.\\nAnnual Value of the enquirer’s place of residence owned by the enquirer of $21,000 or lower.\\nSavings and non-CPF investments of $10,000 or lower if below 60 years old, or $40,000 or lower if aged 60 and above.\\nThe enquirer must not own more than one property.',
        'source_ids': [],
    },
    'faq_279': {
        'number': '279',
        'question': 'What is PDO’s merits test?',
        'match_texts': ["what is pdo's merits test"],
        'answer': 'PDO assesses whether the case has legal merit. This assessment is carried out by PDO.',
        'source_ids': [],
    },
    'faq_281': {
        'number': '281',
        'question': 'How does the enquirer apply for PDO?',
        'match_texts': ['how does the enquirer apply for pdo'],
        'answer': 'The public routes reflected in the FAQ source materials are:\\nApply online: go.gov.sg/applypdo\\nPDO application page: https://pdo.mlaw.gov.sg/criminal-defence-aid/how-to-apply/\\nOr apply in person at the Ministry of Law Services Centre, 45 Maxwell Road #07-11 The URA Centre (East Wing), Singapore 069118, Monday to Friday, 8:30am – 5:00pm. Appointment booking: go.gov.sg/omp\\nOr attend the State Courts Help Centre, 1 Havelock Square #B1-18 State Courts, Singapore 059724, Monday to Friday, 9:00am – 12:00pm and 2:00pm – 5:00pm.',
        'source_ids': [],
    },
    'faq_287': {
        'number': '287',
        'question': 'What are PDO’s contact details?',
        'match_texts': ["what are pdo's contact details"],
        'answer': 'PDO website: https://pdo.mlaw.gov.sg/\\nQualifying for help: https://pdo.mlaw.gov.sg/criminal-defence-aid/qualifying-for-help/\\nHow to apply: https://pdo.mlaw.gov.sg/criminal-defence-aid/how-to-apply/\\nHotline: 1800 2255 529\\nGeneral MinLaw contact page: https://www.mlaw.gov.sg/about-us/contact-us/\\nF. Legal Assistance Scheme for Capital Offences (LASCO)',
        'source_ids': [],
    },
    'faq_294': {
        'number': '294',
        'question': 'What is LASCO?',
        'match_texts': ['what is lasco'],
        'answer': 'LASCO is a scheme linked to the Courts, not PBSG. It offers free legal representation for persons charged with capital offences, regardless of nationality. There is no means test or similar eligibility threshold in the way there is for CLAS or PDO.\\nCourts legal help page: https://www.judiciary.gov.sg/legal-help-support/criminal-case',
        'source_ids': [],
    },
    'faq_297': {
        'number': '297',
        'question': 'How does LASCO work?',
        'match_texts': ['how does lasco work'],
        'answer': 'A person charged with a capital offence is usually assigned legal counsel to represent the person in court. This commonly consists of two practising defence lawyers, one leading and one assisting, who represent the person at trial and on appeal.',
        'source_ids': [],
    },
    'faq_299': {
        'number': '299',
        'question': 'How does the enquirer apply for LASCO?',
        'match_texts': ['how does the enquirer apply for lasco'],
        'answer': 'The person can inform the court at the next hearing, or contact the Courts through:\\nContact page: https://www.judiciary.gov.sg/contact-us\\nHotline: 6587 8423 (6-JUSTICE)\\nHotline: 1800 587 8423 (1800-JUSTICE)\\nMonday to Thursday: 8:30am – 6:00pm\\nFriday: 8:30am – 5:30pm\\nSaturday: 8:30am – 1:00pm for State Courts hearings and bail matters scheduled on Saturday',
        'source_ids': [],
    },
    'faq_307': {
        'number': '307',
        'question': 'What are capital offences?',
        'match_texts': ['what are capital offences'],
        'answer': 'Capital offences are offences that carry the possibility of the death penalty.\\nThe following may be capital offences, depending on the specific charge and circumstances:\\nMurder\\nAssisting the suicide of a vulnerable person\\nKidnapping in certain situations\\nGang robbery with murder\\nUsing or attempting to use a firearm in certain situations\\nTrafficking of firearms in certain situations\\nTrafficking or manufacturing of drugs above certain quantities\\nThis is not legal advice and we are unable to confirm whether the enquirer’s charge is a capital offence without reviewing their documents. The enquirer may wish to check his/her charge sheet, which should indicate the possible punishment of the offence.\\nG. Clinics and General Legal Guidance',
        'source_ids': [],
    },
    'faq_319': {
        'number': '319',
        'question': 'What is a clinic?',
        'match_texts': ['what is a clinic'],
        'answer': 'PBSG clinics provide free basic legal guidance to eligible individuals on their personal legal issues through a 20-minute appointment-only consultation. These sessions are generally one-off and do not include drafting services, legal representation, or specific legal advice.\\nGeneral legal guidance page: https://www.probono.sg/get-legal-help/legal-guidance/',
        'source_ids': [],
    },
    'faq_322': {
        'number': '322',
        'question': 'How much do clinics cost?',
        'match_texts': ['how much do clinics cost'],
        'answer': 'Clinics are free.',
        'source_ids': [],
    },
    'faq_324': {
        'number': '324',
        'question': 'Who is eligible for clinics?',
        'match_texts': ['who is eligible for clinics'],
        'answer': 'As a general guide, the enquirer should meet all the following:\\nThe matter should be a personal legal issue, not a business or commercial issue.\\nIf the issue is linked to business, the matter may still be considered if the enquirer is personally liable, for example as a sole proprietor, personal guarantor for a business loan, a person facing bankruptcy, or a person charged in a personal capacity for a criminal offence.\\nThe enquirer should generally be seeking help on the enquirer’s own matter.\\nThe issue should not already have received legal guidance from another lawyer on the same matter.\\nIf the issue concerns a non-profit, charity, social enterprise, or ground-up initiative, other PBSG avenues may be relevant. Refer to FAQs on Non-Profit Legal Services.',
        'source_ids': [],
    },
    'faq_331': {
        'number': '331',
        'question': 'What locations and modes are available for clinics?',
        'match_texts': ['what locations and modes are available for clinics'],
        'answer': 'Online (Zoom), generally weekdays from 7:00pm – 9:00pm.\\nNorth West CDC: 900 South Woodlands Drive #06-01 Woodlands Civic Centre, Singapore 730900. 1st and 3rd Mondays, 7:30pm – 9:30pm. From 21 April 2025 until further notice, this clinic is temporarily held at Community Law Centre @ Realm of Tranquility, Blk 547 Woodlands Drive 16, Singapore 730547.\\nSouth East CDC: Geylang Wisma Serai, 1 Engku Aman Turn, #03-02, Singapore 408528. 1st and 3rd Tuesdays, 7:00pm – 9:00pm.\\nSouth West CDC: The JTC Summit, 8 Jurong Town Hall Road, #26-06, Singapore 609434. 1st and 3rd Wednesdays, 7:00pm – 9:00pm.\\nCentral Singapore CDC: 490 Lorong 6 Toa Payoh, #07-11 HDB Hub Via Biz Three Lift Lobby 1, Singapore 310490. 1st and 3rd Thursdays, 7:00pm – 9:00pm.\\nNorth East CDC: currently virtual only. 1st Fridays, 7:30pm – 9:30pm.',
        'source_ids': [],
    },
    'faq_338': {
        'number': '338',
        'question': 'How do I apply for clinics?',
        'match_texts': ['how do i apply for clinics'],
        'answer': 'Useful public links include:\\nPBSG legal guidance page: https://www.probono.sg/get-legal-help/legal-guidance/\\nCommunity Legal Clinics Registration Form: https://forms.office.com/Pages/ResponsePage.aspx?id=2SIByMB8W06hRKsXHMIqYg9U_LFeiCRHgqHNQqZ_EfxUMTJZNkhEMUlOMU00WVlUODROTFBMTU5IMyQlQCN0PWcu',
        'source_ids': [],
    },
    'faq_342': {
        'number': '342',
        'question': 'What documents should the enquirer prepare for a clinic application?',
        'match_texts': ['what documents should the enquirer prepare for a clinic application'],
        'answer': 'As a general guide:\\nIdentification document, such as Passport, Employment Pass, Dependant’s Pass, or Long-Term Visit Pass.\\nSupporting documents relevant to the legal issue, for example court documents, contracts, marriage certificate, or correspondence with the other party.',
        'source_ids': [],
    },
    'faq_346': {
        'number': '346',
        'question': 'What if the enquirer cannot make the usual clinic timings?',
        'match_texts': ['what if the enquirer cannot make the usual clinic timings'],
        'answer': 'The enquirer should indicate the reasons in the application form, and PBSG will assess whether alternative accommodations may be possible.',
        'source_ids': [],
    },
    'faq_348': {
        'number': '348',
        'question': 'What if the enquirer cannot travel to the clinic and does not know how to use video call?',
        'match_texts': ['what if the enquirer cannot travel to the clinic and does not know how to use video call'],
        'answer': 'PBSG conducts Zoom trial sessions to guide enquirers through the process before the legal clinic itself. If the enquirer has difficulty travelling or using Zoom, this should be indicated in the application form or explained to PBSG for PBSG to assess whether alternative accommodations may be possible.',
        'source_ids': [],
    },
    'faq_350': {
        'number': '350',
        'question': 'What happens after the enquirer applies for clinics?',
        'match_texts': ['what happens after the enquirer applies for clinics'],
        'answer': 'Generally:\\nPBSG will usually contact the enquirer within 1–2 weeks to update the enquirer on the application.\\nIf the application is approved, PBSG will usually email a suggested appointment date, often around 2–3 weeks from the registration date.\\nTo confirm the appointment, the enquirer must reply within the time stated. If PBSG does not hear back in time, the application may be closed and the slot released to other enquirers.\\nThe enquirer should remain contactable and check email regularly.',
        'source_ids': [],
    },
    'faq_356': {
        'number': '356',
        'question': 'I have already submitted a clinic application. What is the status now?',
        'match_texts': ['i have already submitted a clinic application. what is the status now'],
        'answer': 'The enquirer should first check email, including junk or spam folders. If nothing has been received within the usual timelines, the enquirer may write to legalclinics@probono.sg. If the enquirer is not able to send an email, the frontliner may take down the full name, ID number, contact number, date of application, and any case reference number for follow-up.',
        'source_ids': [],
    },
    'faq_358': {
        'number': '358',
        'question': 'What should the enquirer do if there is a court hearing or deadline in the meantime?',
        'match_texts': ['what should the enquirer do if there is a court hearing or deadline in the meantime'],
        'answer': 'If there is an upcoming court date or deadline, the frontliner should note the urgency and take down the date and any details the enquirer is able to give. The matter should then be escalated to staff to assess what assistance may be possible.\\nH. Community Law Centres (Hougang and Woodlands)',
        'source_ids': [],
    },
    'faq_361': {
        'number': '361',
        'question': 'What are the Community Law Centres? Can I apply?',
        'match_texts': ['what are the community law centres? can i apply'],
        'answer': 'Community Law Centres are PBSG’s branch offices in the heartlands. They were set up to provide legal assistance to persons who may be more socially excluded. PBSG works closely with community partners such as Family Service Centres, Social Service Offices, and other Social Service Agencies to assess whether non-legal help, such as emotional, financial, or social support, is also needed.\\nLike PBSG’s other touchpoints, Community Law Centres triage requests for legal assistance and direct enquirers to the most appropriate avenue of help.\\nFurther information:\\nPBSG launch page: https://www.probono.sg/news/community-law-centre-launch-january-2023/\\nStraits Times (Hougang): https://www.straitstimes.com/singapore/first-community-law-centre-opens-in-hougang?ref=inline-article\\nStraits Times (Woodlands): https://www.straitstimes.com/singapore/pro-bono-sg-opens-its-second-free-community-law-centre-in-woodlands\\nThe enquirer may apply through the clinics registration form, indicating a preference to meet at one of the Community Law Centres and the reasons. If the enquirer needs help, the frontliner may assist to register over the call while reading out all terms and conditions.',
        'source_ids': [],
    },
    'faq_369': {
        'number': '369',
        'question': 'Can I walk in to the Community Law Centres?',
        'match_texts': ['can i walk in to the community law centres'],
        'answer': 'If the enquirer prefers in-person assistance, the enquirer may walk in during office hours:\\nMonday to Friday\\n9:00am – 12:00pm\\n2:00pm – 5:00pm\\nClosed on weekends and public holidays\\nHowever, legal guidance sessions with lawyers are generally not likely to happen on the same day. Legal guidance sessions are generally by appointment so that both the enquirer and the lawyer have sufficient time to prepare, and they remain subject to PBSG’s eligibility criteria.',
        'source_ids': [],
    },
    'faq_376': {
        'number': '376',
        'question': 'Is there a phone number for the Community Law Centres?',
        'match_texts': ['is there a phone number for the community law centres'],
        'answer': 'No. Enquiries are handled through PBSG’s centralised hotline. Frontliners can answer questions about the Community Law Centres and assist enquirers to apply for PBSG’s services through the central hotline.',
        'source_ids': [],
    },
    'faq_378': {
        'number': '378',
        'question': 'When are Community Law Centre consultations usually held?',
        'match_texts': ['when are community law centre consultations usually held'],
        'answer': 'Legal consultations at Community Law Centres are generally held on Tuesdays and Thursdays, from 10:00am to 4:00pm.',
        'source_ids': [],
    },
    'faq_380': {
        'number': '380',
        'question': 'What is the difference between the CDC clinics and the Community Law Centres?',
        'match_texts': ['what is the difference between the cdc clinics and the community law centres'],
        'answer': 'Community Law Centres are generally reserved for more vulnerable individuals who may need more than legal support alone, because PBSG may work together with community partners such as social workers and caseworkers from Family Service Centres, Social Service Offices, and other Social Service Agencies, to provide social and financial support.\\nCDC clinics are generally held on weekday evenings. Community Law Centre sessions are generally held on Tuesdays and Thursdays, from 10:00am to 4:00pm.\\nI. Transnational Family Care Centre (TFCC)',
        'source_ids': [],
    },
    'faq_384': {
        'number': '384',
        'question': 'What is the Transnational Family Care Centre (TFCC)?',
        'match_texts': ['what is tfcc', 'what is the transnational family care centre (tfcc)'],
        'answer': 'TFCC is a collaborative effort between South Central Community Family Service Centre and Pro Bono SG, set up to assist low-income and vulnerable transnational families.\\nPBSG provides legal guidance to eligible individuals while partners such as SCCFSC may be able to support with financial, medical, and social assistance.\\nFurther information:\\nPBSG page: https://www.probono.sg/get-legal-help/legal-guidance/a-transnation-family/\\nSCCFSC page: https://sccfsc.sg/pages/tfcc\\nLaunch press release: https://www.probono.sg/wp-content/uploads/2024/07/Transnational-Family-Care-Centre-Launch-Press-Release-Final-15-Jul.pdf',
        'source_ids': [],
    },
    'faq_391': {
        'number': '391',
        'question': 'Who may apply to TFCC?',
        'match_texts': ['who may apply to tfcc'],
        'answer': 'If the enquirer is a low-income foreigner with a Singaporean in the family and is seeking legal assistance, the enquirer may submit an application through PBSG’s clinics registration form, indicating the family circumstances, and PBSG will assess whether assistance may be possible.',
        'source_ids': [],
    },
    'faq_393': {
        'number': '393',
        'question': 'What if the enquirer also needs financial, medical, or social assistance?',
        'match_texts': ['what if the enquirer also needs financial, medical, or social assistance'],
        'answer': 'The enquirer should indicate this in the application form and may also reach out directly to SCCFSC:\\nEmail: theinclusivefund@sccfsc.org.sg\\nPhone: 6461 9200\\nSouth Central Community Family Service Centre\\nBlk 5 Delta Avenue #01-09\\nSingapore 160005\\nOpening hours: Monday 10:00am – 9:00pm; Tuesday to Friday 10:00am – 6:30pm; closed on public holidays.',
        'source_ids': [],
    },
    'faq_401': {
        'number': '401',
        'question': 'What is considered “low-income” for TFCC?',
        'match_texts': ['what is considered "low-income" for tfcc'],
        'answer': 'PBSG and SCCFSC are charities with limited resources. The services are generally meant for people who are not able to afford paid services. Once the application form is submitted, the matter will be assessed holistically to determine whether the enquirer qualifies.\\nJ. Migrant Workers’ Law Centre (MWLC)',
        'source_ids': [],
    },
    'faq_404': {
        'number': '404',
        'question': 'What is the Migrant Workers’ Law Centre @ Migrant Workers’ Centre?',
        'match_texts': ['what is mwlc', "what is the migrant workers' law centre @ migrant workers' centre"],
        'answer': 'The Migrant Workers’ Law Centre is a collaborative effort between the Migrant Workers’ Centre and Pro Bono SG, set up to assist migrant workers.\\nThe Migrant Workers’ Centre is a bipartite effort between NTUC and the Singapore National Employers Federation. PBSG provides legal guidance to eligible enquirers while MWC may be able to support with financial, medical, and social assistance.\\nFurther information:\\nPBSG page: https://www.probono.sg/get-legal-help/legal-guidance/the-migrant-worker-community/\\nMWC page: https://www.mwc.org.sg/how-we-help/migrant-workers-law-centre-at-mwc\\nLaunch press release: https://www.probono.sg/press-room/launch-of-migrant-workers-law-centre-to-enhance-legal-support-for-migrant-workers/',
        'source_ids': [],
    },
    'faq_411': {
        'number': '411',
        'question': 'How do I contact MWLC?',
        'match_texts': ['how do i contact mwlc'],
        'answer': 'The details reflected in the FAQ source materials are:\\nMigrant Workers’ Law Centre @ MWC\\n579 Serangoon Road\\nSingapore 218193\\nMonday: 9:00am – 5:45pm (virtual)\\nTuesday – Friday: 9:00am – 5:45pm\\nSaturday: 11:00am – 3:00pm (virtual)\\nWhatsApp / Call: 8764 8298\\nEmail: migrantworkers@probono.sg\\nMigrant Worker Legal Clinic @ Angullia Mosque\\n265 Serangoon Road\\nSingapore 218099\\n2nd Sunday of every month\\n10:00am – 12:30pm',
        'source_ids': [],
    },
    'faq_426': {
        'number': '426',
        'question': 'How does a migrant worker apply for help from MWLC?',
        'match_texts': ['how does a migrant worker apply for help from mwlc'],
        'answer': 'The migrant worker may submit an application through MWLC’s registration form, and PBSG will assess whether assistance may be possible. Alternatively, the migrant worker may walk-in to MWLC for assistance or call 8764 8298 during MWLC’s operating hours.\\nForm link: https://forms.office.com/pages/responsepage.aspx?id=2SIByMB8W06hRKsXHMIqYpurCEtny3lDq5-OFqeu0TpUQ0c5M01USzlGQVFKRDYwTkZSS0cwRFZWSy4u&route=shorturl',
        'source_ids': [],
    },
    'faq_429': {
        'number': '429',
        'question': 'What if the migrant worker also needs non-legal help?',
        'match_texts': ['what if the migrant worker also needs non-legal help'],
        'answer': 'The migrant worker should indicate this in the application form and may also reach out directly to MWC. Details reflected in the materials are:\\nMWC Help Centre\\n579 Serangoon Road\\nSingapore 218193\\nTuesdays to Fridays: 9:00am – 7:00pm\\nSaturdays and Sundays: 11:00am – 3:00pm\\nMondays and public holidays: closed\\nK. Inclusive Justice Law Centre (IJLC)',
        'source_ids': [],
    },
    'faq_438': {
        'number': '438',
        'question': 'What is the Inclusive Justice Law Centre?',
        'match_texts': ['what is ijlc', 'what is the inclusive justice law centre'],
        'answer': 'The Inclusive Justice Law Centre serves as a dedicated touchpoint aimed at supporting individuals with invisible disabilities and their caregivers through targeted outreach and awareness efforts. Like PBSG’s other touchpoints, IJLC triages requests for legal assistance and directs enquirers to the most appropriate avenue of help.\\nThe intended beneficiaries include individuals with invisible disabilities, including neurodevelopmental conditions, mental health conditions, psychiatric illnesses, or cognitive or developmental disabilities, who face barriers when navigating legal matters and who are unable to afford paid legal services.\\nFurther reading:\\nCNA article: https://www.channelnewsasia.com/singapore/inclusive-justice-law-centre-special-needs-mental-health-conditions-5998271\\nStraits Times article: https://www.straitstimes.com/singapore/new-law-centre-to-help-those-with-special-needs-mental-health-conditions-navigate-legal-system',
        'source_ids': [],
    },
    'faq_444': {
        'number': '444',
        'question': 'How does someone apply for IJLC-related help?',
        'match_texts': ['how does someone apply for ijlc-related help'],
        'answer': 'The person may submit an application through PBSG’s clinics registration form, indicating the relevant circumstances, and PBSG will assess what assistance may be possible.\\nL. Family Justice Support Scheme (FJSS)',
        'source_ids': [],
    },
    'faq_447': {
        'number': '447',
        'question': 'What is FJSS?',
        'match_texts': ['what is fjss'],
        'answer': 'FJSS is PBSG’s legal representation scheme for selected family matters. It covers:\\nDivorce, including divorces under Syariah law.\\nVariation or enforcement of court orders on ancillary matters in a divorce, for example custody of children or division of assets.\\nChildren-related issues such as custody, care and control, access, or relocation.\\nProceedings in the Family Court for maintenance and family violence, but only where the opposing party is legally represented.',
        'source_ids': [],
    },
    'faq_453': {
        'number': '453',
        'question': 'How much does FJSS cost?',
        'match_texts': ['how much does fjss cost'],
        'answer': 'FJSS ranges from free to lower-cost, depending on the pathway.\\nFJSS Pro Bono: lawyer’s professional fees are not charged, although there may be a co-payment and/or disbursements depending on the enquirer’s financial circumstances and the case.\\nFJSS Modest Means: there is no fixed rate because each lawyer charges differently, but FJSS Modest Means panel lawyers commit to charging less than their usual commercial rates.',
        'source_ids': [],
    },
    'faq_457': {
        'number': '457',
        'question': 'What are the eligibility criteria for FJSS?',
        'match_texts': ['what are the eligibility criteria for fjss'],
        'answer': 'The enquirer must not already be legally represented, unless the current lawyer is willing to take on the case under PBSG and PBSG approves.\\nThe enquirer’s case is covered by FJSS. Generally:\\nDivorce, including divorces under Syariah law.\\nVariation or enforcement of court orders on ancillary matters in a divorce, for example custody of children or division of assets.\\nChildren-related issues such as custody, care and control, access, or relocation.\\nProceedings in the Family Court for maintenance and family violence, but only where the opposing party is legally represented.\\nThe enquirer must pass the means and merits tests.\\nFor Singaporeans and Permanent Residents seeking FJSS Modest Means, the enquirer must already have been rejected by LAB and should provide the rejection letter or notification.\\nFor foreign spouses with Singaporean children, FJSS Pro Bono may be relevant if the enquirer passes the applicable means and merits criteria and the matter falls within scope.',
        'source_ids': [],
    },
    'faq_467': {
        'number': '467',
        'question': 'What is the means test for FJSS Pro Bono?',
        'match_texts': ['what is the means test for fjss pro bono'],
        'answer': 'PCHI of $1,050 or lower for the last 12 months before the application.\\nAnnual Value of the enquirer’s place of residence owned by the enquirer of $21,000 or lower.\\nSavings and non-CPF investments of $10,000 or lower if below 60 years old, or $40,000 or lower if aged 60 and above.',
        'source_ids': [],
    },
    'faq_471': {
        'number': '471',
        'question': 'What is the means test for FJSS Modest Means?',
        'match_texts': ['what is the means test for fjss modest means'],
        'answer': 'Average PCHI of $1,400 or lower for the last 12 months before the application.\\nAnnual Value of the enquirer’s place of residence owned by the enquirer of $21,000 or lower.\\nSavings and non-CPF investments of $12,000 or lower if below 60 years old, or $48,000 or lower if aged 60 and above.',
        'source_ids': [],
    },
    'faq_475': {
        'number': '475',
        'question': 'What is the merits test for FJSS?',
        'match_texts': ['what is the merits test for fjss'],
        'answer': 'The enquirer will be interviewed by a lawyer on the legal issue and personal circumstances so PBSG can assess the strength of the case. Additional documents may be requested.',
        'source_ids': [],
    },
    'faq_477': {
        'number': '477',
        'question': 'Can I still apply for FJSS if I am currently represented by a lawyer?',
        'match_texts': ['can i still apply for fjss if i am currently represented by a lawyer'],
        'answer': 'PBSG generally does not accept applications from individuals who are already represented by a lawyer, unless that lawyer is willing to take on the case under Pro Bono SG and PBSG approves. Frontliners should not advise enquirers to discharge their lawyers. Any decision made by the enquirer to discharge or not discharge their lawyers should be made without influence or advice from us. There are other eligibility criteria to be fulfilled, and PBSG is unable to guarantee that aid will be granted upon the enquirer’s discharge of lawyer.',
        'source_ids': [],
    },
    'faq_479': {
        'number': '479',
        'question': 'How does someone apply for FJSS?',
        'match_texts': ['how does someone apply for fjss'],
        'answer': 'The enquirer may apply online through PBSG’s legal representation page or directly through the public application form link:\\nPBSG legal representation page: https://www.probono.sg/get-legal-help/legal-representation/\\nFJSS Application Form: https://form.jotform.com/232941651541454',
        'source_ids': [],
    },
    'faq_483': {
        'number': '483',
        'question': 'What if the enquirer does not know how to use the internet for an FJSS application?',
        'match_texts': ['what if the enquirer does not know how to use the internet for an fjss application'],
        'answer': 'The enquirer may bring documents and go to one of PBSG’s offices. Generally:\\nIdentification document, such as Passport, Employment Pass, Dependant’s Pass, or Long-Term Visit Pass.\\nMarriage certificate.\\nChild’s birth certificate.\\nCourt or other legal documents, if any, such as court orders, court applications, or letters from the spouse’s lawyer.\\nSupporting documents relevant to the case, if any, such as photographs, medical reports, police reports, or evidence of maintenance.',
        'source_ids': [],
    },
    'faq_490': {
        'number': '490',
        'question': 'What if the enquirer does not have the FJSS documents requested?',
        'match_texts': ['what if the enquirer does not have the fjss documents requested'],
        'answer': 'The enquirer should write to fjss@probono.sg explaining why the documents are unavailable.',
        'source_ids': [],
    },
    'faq_492': {
        'number': '492',
        'question': 'What happens after an FJSS application is submitted?',
        'match_texts': ['what happens after an fjss application is submitted'],
        'answer': 'Generally:\\nPBSG will usually contact the enquirer within 1–2 weeks to update the enquirer on the application. This may take longer if more information or documents are needed.\\nIf the application is approved, it will generally take a further 2–4 weeks for a volunteer lawyer to be assigned.\\nThe enquirer should remain contactable and check email regularly.',
        'source_ids': [],
    },
    'faq_497': {
        'number': '497',
        'question': 'I have already submitted my FJSS application. What is the status now?',
        'match_texts': ['i have already submitted my fjss application. what is the status now'],
        'answer': 'The enquirer should first check email. If nothing has been received within the usual timelines, the enquirer may write to fjss@probono.sg. If the enquirer is unable to email, the frontliner may take down the full name, date of application, and any case reference number for follow-up.',
        'source_ids': [],
    },
    'faq_499': {
        'number': '499',
        'question': 'What should the enquirer do if there is a court hearing or deadline while the FJSS application is pending?',
        'match_texts': ['what should the enquirer do if there is a court hearing or deadline while the fjss application is pending'],
        'answer': 'The enquirer should be reminded that while the application is pending, PBSG is not yet representing the enquirer. The enquirer may try to ask the court for an adjournment or extension of time and let the court know that an application has been made to PBSG under FJSS and that the enquirer is waiting to hear back.',
        'source_ids': [],
    },
    'faq_501': {
        'number': '501',
        'question': 'Can PBSG write to the court to say that an FJSS application is being processed?',
        'match_texts': ['can pbsg write to the court to say that an fjss application is being processed'],
        'answer': 'No. However, the enquirer may show the court the acknowledgement email received from PBSG upon application.\\nM. Criminal Legal Aid Scheme (CLAS)',
        'source_ids': [],
    },
    'faq_504': {
        'number': '504',
        'question': 'What is CLAS?',
        'match_texts': ['what is clas'],
        'answer': 'CLAS is PBSG’s legal representation scheme for low-income foreigners who have already been charged in court. It applies to criminal matters that fall within CLAS’s scope.\\nServices are provided on a pro bono basis, meaning the lawyer’s professional fees are generally not charged, although the enquirer may still need to make a co-payment depending on financial circumstances and/or pay disbursements such as court filing fees or medical report fees.\\nPBSG legal representation page: https://www.probono.sg/get-legal-help/legal-representation/',
        'source_ids': [],
    },
    'faq_508': {
        'number': '508',
        'question': 'How much does CLAS cost?',
        'match_texts': ['how much does clas cost'],
        'answer': 'CLAS is generally free to low-cost. There may be a co-payment depending on the enquirer’s financial circumstances. PBSG will usually only be able to indicate the amount after the application and financial documents have been received and assessed.',
        'source_ids': [],
    },
    'faq_510': {
        'number': '510',
        'question': 'What are the main eligibility criteria for CLAS?',
        'match_texts': ['what are the main eligibility criteria for clas'],
        'answer': 'The key points are:\\nThe enquirer must not already be legally represented, unless the current lawyer is willing to take the case on under Pro Bono SG and PBSG approves.\\nThe enquirer must pass the means and merits tests.\\nThe enquirer must already have been charged in court for an offence that is not excluded by CLAS.',
        'source_ids': [],
    },
    'faq_515': {
        'number': '515',
        'question': 'What offences does CLAS not handle?',
        'match_texts': ['what offences does clas not handle'],
        'answer': 'CLAS does not handle:\\nOffences punishable by death.\\nOffences that are regulatory in nature, for example traffic summonses, and departmental charges.\\nOffences under certain Acts relating to gambling, organised or syndicate crime, and terrorism.\\nOffences prosecuted by a private person.',
        'source_ids': [],
    },
    'faq_521': {
        'number': '521',
        'question': 'Which Acts are excluded under CLAS for gambling, organised crime, and terrorism?',
        'match_texts': ['which acts are excluded under clas for gambling, organised crime, and terrorism'],
        'answer': 'Betting Act 1960\\nCasino Control Act 2006\\nCommon Gaming Houses Act 1961\\nGambling Control Act 2022\\nMassage Establishments Act 2017\\nOrganised Crime Act 2015\\nRemote Gambling Act 2014\\nTerrorism (Suppression of Bombings) Act 2007\\nTerrorism (Suppression of Financing) Act 2002\\nTerrorism (Suppression of Misuse of Radioactive Material) Act 2017',
        'source_ids': [],
    },
    'faq_532': {
        'number': '532',
        'question': 'Which regulatory Acts are excluded under CLAS?',
        'match_texts': ['which regulatory acts are excluded under clas'],
        'answer': 'Advance Medical Directive Act 1996\\nChild Development Co-Savings Act 2001\\nCustoms Act 1960\\nEmployment Act 1968\\nEmployment Agencies Act 1958\\nEmployment Claims Act 2016\\nEmployment of Foreign Manpower Act 1990\\nEnlistment Act 1970\\nFire Safety Act 1993\\nForeign Employee Dormitories Act 2015\\nGoods and Services Tax Act 1993\\nHealth Products Act 2007\\nHealth Promotion Board Act 2001\\nHealth Sciences Authority Act 2001\\nImmigration Act 1959\\nInfectious Diseases Act 1976\\nInsolvency, Restructuring and Dissolution Act 2018\\nMedical and Elderly Care Endowment Schemes Act 2000\\nMedicines (Advertisement and Sale) Act 1955\\nMedicines Act 1975\\nMoneylenders Act 2008\\nNational Registration Act 1965\\nPassports Act 2007\\nPersonal Data Protection Act 2012\\nPoisons Act 1938\\nRegistration of Births and Deaths Act 2021\\nRegulation of Imports and Exports Act 1995\\nRetirement and Re-employment Act 1993\\nRoad Traffic Act 1961\\nSale of Drugs Act 1914\\nSingapore Armed Forces Act 1972\\nTermination of Pregnancy Act 1974\\nTobacco (Control of Advertisements and Sale) Act 1993\\nTraditional Chinese Medicine Practitioners Act 2000\\nWork Injury Compensation Act 2019\\nWorkplace Safety and Health Act 2006\\nTown Councils Act 1988\\nBankruptcy Act (Cap 20, 2009 Rev Ed)\\nPawnbrokers Act 2015',
        'source_ids': [],
    },
    'faq_572': {
        'number': '572',
        'question': 'What is the means test for CLAS?',
        'match_texts': ['what is the means test for clas'],
        'answer': 'The thresholds reflected in the FAQ source materials are:\\nAverage PCHI of $1,650 or lower for the last 12 months before the application.\\nAnnual Value of the enquirer’s place of residence owned by the enquirer of $21,000 or lower.\\nSavings and non-CPF investments of $10,000 or lower if below 60 years old, or $40,000 or lower if aged 60 and above.\\nThe enquirer must not own any property besides the place of residence.',
        'source_ids': [],
    },
    'faq_578': {
        'number': '578',
        'question': 'What is CLAS’ merits test?',
        'match_texts': ["what is clas' merits test"],
        'answer': 'The enquirer will be interviewed by a lawyer on the legal issue and personal circumstances so PBSG can assess the strength of the case. Additional documents may be requested.',
        'source_ids': [],
    },
    'faq_580': {
        'number': '580',
        'question': 'Can I still apply for CLAS if I am currently represented by a lawyer?',
        'match_texts': ['can i still apply for clas if i am currently represented by a lawyer'],
        'answer': 'PBSG generally does not accept applications from individuals who are already represented by a lawyer, unless that lawyer is willing to take on the case under Pro Bono SG and PBSG approves. Frontliners should not advise enquirers to discharge their lawyers. Any decision made by the enquirer to discharge or not discharge their lawyers should be made without influence or advice from us. There are other eligibility criteria to be fulfilled, and PBSG is unable to guarantee that aid will be granted upon the enquirer’s discharge of lawyer.',
        'source_ids': [],
    },
    'faq_582': {
        'number': '582',
        'question': 'How does someone apply for CLAS?',
        'match_texts': ['how does someone apply for clas'],
        'answer': 'The enquirer may apply online through PBSG’s legal representation page or directly through the public application form link reflected in the source materials:\\nPBSG legal representation page: https://www.probono.sg/get-legal-help/legal-representation/\\nCLAS Application Form: https://form.jotform.com/241692509744464',
        'source_ids': [],
    },
    'faq_586': {
        'number': '586',
        'question': 'What if the enquirer does not know how to use the internet for a CLAS application?',
        'match_texts': ['what if the enquirer does not know how to use the internet for a clas application'],
        'answer': 'The enquirer may bring documents and go to one of PBSG’s offices. The documents generally mentioned include:\\nFor the enquirer: Bail Bond, Charge Sheet(s), Latest Mention Slip, IRAS Notice of Assessment for the past year if self-employed, payslips for the past 12 months, bank balance slips for all bank accounts dated within 7 days of application, insurance documents stating surrender value, and investment documents stating current market value.\\nFor working household members: CPF contribution history for the past 15 months, IRAS Notice of Assessment for the past year, and payslips for the past 12 months if relevant.',
        'source_ids': [],
    },
    'faq_590': {
        'number': '590',
        'question': 'What if the enquirer does not have the CLAS documents requested?',
        'match_texts': ['what if the enquirer does not have the clas documents requested'],
        'answer': 'The enquirer may first refer to PBSG’s information sheet on how to extract the documents needed: https://www.probono.sg/wp-content/uploads/2025/03/CLAS-Information-Sheet-for-Applicants-as-of-7-Mar-2025.pdf\\nIf the enquirer is still unable to provide the documents, the enquirer should write to clas@probono.sg explaining why.',
        'source_ids': [],
    },
    'faq_593': {
        'number': '593',
        'question': 'What happens after a CLAS application is submitted?',
        'match_texts': ['what happens after a clas application is submitted'],
        'answer': 'The usual process is:\\nPBSG will usually contact the enquirer within 1–2 weeks to update the enquirer on the application. This may take longer if more information or documents are needed.\\nIf the application is approved, it will generally take a further 2–4 weeks for a volunteer lawyer to be assigned.\\nThe enquirer should remain contactable and check email regularly.',
        'source_ids': [],
    },
    'faq_598': {
        'number': '598',
        'question': 'I have already submitted my CLAS application. What is the status now?',
        'match_texts': ['i have already submitted my clas application. what is the status now'],
        'answer': 'The enquirer should first check email. If nothing has been received within the usual timelines, the enquirer may write to clas@probono.sg. If the enquirer is unable to email, the frontliner may take down the full name, date of application, and any case reference number for follow-up.',
        'source_ids': [],
    },
    'faq_600': {
        'number': '600',
        'question': 'What should the enquirer do if there is a court hearing or deadline while the CLAS application is pending?',
        'match_texts': ['what should the enquirer do if there is a court hearing or deadline while the clas application is pending'],
        'answer': 'The enquirer should be reminded that while the application is pending, PBSG is not yet representing the enquirer. The enquirer may try to ask the court for an adjournment or extension of time and let the court know that an application has been made to PBSG under CLAS and that the enquirer is waiting to hear back.',
        'source_ids': [],
    },
    'faq_602': {
        'number': '602',
        'question': 'Can PBSG write to the court to say that a CLAS application is being processed?',
        'match_texts': ['can pbsg write to the court to say that a clas application is being processed'],
        'answer': 'No. However, the enquirer may show the court the acknowledgement email received from PBSG upon application.\\nN. Other Services and Practical Matters',
        'source_ids': [],
    },
    'faq_605': {
        'number': '605',
        'question': 'Why are you referring me to LAB or PDO?',
        'match_texts': ['why are you referring me to lab or pdo'],
        'answer': 'Some cases fall under Government legal aid schemes. These agencies may be better placed to assist. PBSG is a charity with limited resources and needs to prioritise those who are unable to seek help elsewhere. LAB and PDO are under the Ministry of Law and are specifically set up to assist low-income Singaporeans and Permanent Residents. Some Government legal aid schemes may also have statutory powers that can help them move matters along more quickly, for example seeking a stay of proceedings (pause of the court case) while legal aid is being processed, seeking waiver of certain court fees, or coordinating with other Government agencies.',
        'source_ids': [],
    },
    'faq_607': {
        'number': '607',
        'question': 'Can I choose not to go to LAB or PDO and ask PBSG to help instead?',
        'match_texts': ['can i choose not to go to lab or pdo and ask pbsg to help instead'],
        'answer': 'It depends on the type of help sought. For legal guidance, PBSG may still be able to assist if the enquirer meets PBSG’s eligibility criteria. For legal representation, enquirers who are eligible for LAB or PDO would generally need to approach those schemes first.',
        'source_ids': [],
    },
    'faq_609': {
        'number': '609',
        'question': 'Can you help draft documents or send letters for me?',
        'match_texts': ['can you help draft documents or send letters for me'],
        'answer': 'At PBSG legal guidance sessions, the lawyer providing legal guidance does not act for the enquirer. Because of that, the lawyer is unable to draft documents or send letters on the enquirer’s behalf during these one-off sessions. For legal representation matters, if the enquirer qualifies and a lawyer is assigned or engaged under the scheme, the lawyer may act and take those steps if appropriate.',
        'source_ids': [],
    },
    'faq_611': {
        'number': '611',
        'question': 'Can you help me prepare a will or Lasting Power of Attorney?',
        'match_texts': ['can you help me prepare a will or lasting power of attorney'],
        'answer': 'PBSG does not provide will-writing services or LPA making or certificate issuing services. Resources that may help include:\\nOffice of the Public Guardian on making an LPA: https://www.msf.gov.sg/what-we-do/opg/lasting-power-of-attorney/how-to-make-a-lasting-power-of-attorney\\nGovernment Health Appointment System list of LPA Certificate Issuers: https://book.health.gov.sg/lpa\\nOPG list of organisations that may assist with free certificate-issuing services for those facing financial difficulties: https://www.msf.gov.sg/what-we-do/opg/lasting-power-of-attorney/where-to-find-a-certificate-issuer\\nMy Legacy guide on making a will: https://mylegacy.life.gov.sg/end-of-life-planning/write-a-will/how-to-write-a-will/\\nLAB website: https://lab.mlaw.gov.sg/ (will writing only; LAB does not assist with LPA making or certificate issuing)\\nLAB eligibility page: https://lab.mlaw.gov.sg/legal-services/do-i-qualify/\\nOneMinLaw portal to make an appointment for LAB: https://eservices.mlaw.gov.sg/auth/login',
        'source_ids': [],
    },
    'faq_620': {
        'number': '620',
        'question': 'Can you notarise documents or act as Commissioner for Oaths?',
        'match_texts': ['can you notarise documents or act as commissioner for oaths'],
        'answer': 'No. PBSG does not provide commissioning or notary services. The Singapore Academy of Law’s directory may help: https://legalisation.sal.sg/',
        'source_ids': [],
    },
    'faq_622': {
        'number': '622',
        'question': 'Can someone accompany me to my appointment?',
        'match_texts': ['can someone accompany me to my appointment'],
        'answer': 'Generally, PBSG only allows the person applying for legal help to be at the session. However, if there is a special need for an accompanying person, for example interpretation, emotional support, or assistance with navigating systems, this should be indicated in the application form and PBSG will assess. Depending on the case and the accompanying person’s involvement, the lawyer may decide it is best to speak with the enquirer directly.',
        'source_ids': [],
    },
    'faq_624': {
        'number': '624',
        'question': 'Can you provide interpretation?',
        'match_texts': ['can you provide interpretation'],
        'answer': 'Where possible, PBSG may ask whether the enquirer has a trusted individual, such as a family member or friend, who can assist. If not, the enquirer should indicate the preferred language in the application form and PBSG will assess what arrangements may be possible. If the frontliner is helping with the application, the frontliner should indicate the language difficulty and relevant reasons clearly in the form.',
        'source_ids': [],
    },
    'faq_626': {
        'number': '626',
        'question': 'I am under 18 years old. Can you help me?',
        'match_texts': ['i am under 18 years old. can you help me'],
        'answer': 'Please escalate this matter to staff, for staff to take over interaction with the minor. PBSG generally requires a trusted adult to be present for consultations involving minors. If the enquirer has a relative, social worker, or friend who can attend, that should be indicated. If not, PBSG may consider waiving the requirement in exceptional circumstances. The circumstances should be set out clearly in the application form.',
        'source_ids': [],
    },
    'faq_628': {
        'number': '628',
        'question': 'Are my information and case confidential?',
        'match_texts': ['are my information and case confidential'],
        'answer': 'Yes. Information provided to PBSG will be kept confidential and will generally only be shared with relevant PBSG team members, volunteers, and, where necessary, partners involved in assessing or providing assistance. The information will also be kept for record purposes. PBSG generally does not delete the information simply because an application was unsuccessful or because the enquirer did not attend a clinic session.',
        'source_ids': [],
    },
    'faq_630': {
        'number': '630',
        'question': 'Why do you need so much information from me?',
        'match_texts': ['why do you need so much information from me'],
        'answer': 'PBSG needs enough information to assess eligibility and determine how it may be able to help. Without sufficient information, PBSG may not be able to provide accurate guidance about the available avenues of help.',
        'source_ids': [],
    },
    'faq_632': {
        'number': '632',
        'question': 'What should I do if PBSG cannot help me?',
        'match_texts': ['what should i do if pbsg cannot help me'],
        'answer': 'PBSG will generally try to provide general next steps on where else the enquirer may seek assistance, depending on the issue. If appropriate, the frontliner should move into the relevant triage questions so the most sensible referral can be identified.',
        'source_ids': [],
    },
    'faq_634': {
        'number': '634',
        'question': 'Can you recommend me a lawyer?',
        'match_texts': ['can you recommend me a lawyer'],
        'answer': 'PBSG does not recommend specific lawyers. However, frontliners may point enquirers to lawyer directories such as:\\nSingapore Legal Advice: https://singaporelegaladvice.com/\\nLaw Society of Singapore directory: https://www.lawsociety.org.sg/find-a-featured-lawyer-law-firm/\\nLegal Services Regulatory Authority lawyer search: https://eservices.mlaw.gov.sg/lsra/search-lawyer-or-law-firm/',
        'source_ids': [],
    },
    'faq_639': {
        'number': '639',
        'question': 'Can you help me if I had a lawyer previously but the lawyer did not handle the case well?',
        'match_texts': ['can you help me if i had a lawyer previously but the lawyer did not handle the case well'],
        'answer': 'The enquirer should explain the circumstances in the application form, and PBSG will assess whether it may be able to assist.',
        'source_ids': [],
    },
    'faq_641': {
        'number': '641',
        'question': 'Can you help me with a dispute I have with my lawyer?',
        'match_texts': ['can you help me with a dispute i have with my lawyer'],
        'answer': 'Generally, PBSG is unable to advise on disputes with lawyers. The Law Society of Singapore’s page on complaints against lawyers may be helpful: https://www.lawsociety.org.sg/file-a-complaint/',
        'source_ids': [],
    },
    'faq_643': {
        'number': '643',
        'question': 'Can you help translate my document for court use?',
        'match_texts': ['can you help translate my document for court use'],
        'answer': 'Generally, PBSG is unable to assist with translation of documents, unless the enquirer has already qualified for one of PBSG’s representation schemes and translation falls within support that may be arranged in that context.',
        'source_ids': [],
    },
    'faq_645': {
        'number': '645',
        'question': 'I am calling on behalf of a non-profit and need help. Can PBSG help?',
        'match_texts': ['i am calling on behalf of a non-profit and need help. can pbsg help'],
        'answer': 'PBSG may be able to assist a non-profit, charity, social enterprise, or ground-up initiative. Eligibility criteria are available here: https://www.probono.sg/wp-content/uploads/2025/07/3.7.25.pdf. The enquirer may email nls@probono.sg, or the frontliner may take down the entity name, contact details, and short description of the legal issue for follow-up.',
        'source_ids': [],
    },
    'faq_647': {
        'number': '647',
        'question': 'I missed my appointment or interview. Can I get a new appointment?',
        'match_texts': ['i missed my appointment or interview. can i get a new appointment'],
        'answer': 'The enquirer should write to the relevant PBSG team and PBSG will let the enquirer know whether re-scheduling is possible.\\nlegalclinics@probono.sg for clinic-related matters\\nclas@probono.sg for CLAS matters\\nfjss@probono.sg for FJSS matters\\nhelp@probono.sg if the enquirer is unsure which PBSG scheme is relevant\\nO. General Enquiries, Difficult Conversations, and Emergency / Non-Legal Support',
        'source_ids': [],
    },
    'faq_654': {
        'number': '654',
        'question': 'How can I volunteer or sign up for an internship?',
        'match_texts': ['how can i volunteer or sign up for an internship'],
        'answer': 'PBSG has a range of opportunities with different levels of commitment and experience. Volunteer page: https://www.probono.sg/get-involved/volunteer/\\nVolunteer contact email: volunteer@probono.sg\\nIf preferred, the frontliner may also take down contact details for the relevant team to follow up.',
        'source_ids': [],
    },
    'faq_658': {
        'number': '658',
        'question': 'How can I donate?',
        'match_texts': ['how can i donate'],
        'answer': 'PBSG’s donation page is: https://www.probono.sg/donate-now/\\nThe page sets out channels such as PayNow, one-time or recurring card payments, bank transfers, giving.sg, and fundraising initiatives.\\nIf preferred, the frontliner may also take down contact details for the relevant team to follow up.',
        'source_ids': [],
    },
    'faq_662': {
        'number': '662',
        'question': 'How can I register for talks and events?',
        'match_texts': ['how can i register for talks and events'],
        'answer': 'The enquirer may write to academy@probono.sg to ask to be added to the mailing list. The enquirer may also keep a lookout on PBSG’s public channels:\\nYouTube: https://www.youtube.com/@probono_sg\\nLinkedIn: https://www.linkedin.com/company/probonosg',
        'source_ids': [],
    },
    'faq_670': {
        'number': '670',
        'question': '“You are all lawyers, right?”',
        'match_texts': ['you are all lawyers, right', 'you are all lawyers, right?'],
        'answer': 'Our frontliners may not be lawyers and are generally not able to provide immediate legal guidance at the triaging stage. However, we do have lawyers who may be able to assist. If the enquirer is able to answer a few questions, we can provide more information on a suitable avenue of help and its eligibility criteria.',
        'source_ids': [],
    },
    'faq_676': {
        'number': '676',
        'question': '“Can you hurry up?”',
        'match_texts': ['can you hurry up', 'can you hurry up?'],
        'answer': 'If there is urgency, for example an upcoming deadline or court date, PBSG should be told immediately, and PBSG will take note and try its best to expedite where possible. For all urgent matters, please escalate to staff immediately.',
        'source_ids': [],
    },
    'faq_678': {
        'number': '678',
        'question': '“Can I complain?”',
        'match_texts': ['can i complain', 'can i complain?'],
        'answer': 'We are open to feedback that could help us improve our services. Please write to help@probono.sg. If you have a case reference number, that would be helpful for us to better understand your feedback.',
        'source_ids': [],
    },
}


_DOCUMENT_FAQ_LOOKUP: dict[str, tuple[str, dict[str, Any]]] = {}
for _faq_key, _faq in PBSG_DOCUMENT_FAQS.items():
    for _match_text in _faq.get("match_texts", []):
        _DOCUMENT_FAQ_LOOKUP[_match_text] = (_faq_key, _faq)


def document_faq_match(text: str) -> tuple[str, dict[str, Any]] | None:
    normalized = normalize_document_faq_text(text)
    if not normalized:
        return None
    return _DOCUMENT_FAQ_LOOKUP.get(normalized)


def is_document_faq_query(text: str) -> bool:
    return document_faq_match(text) is not None
